### ISSUE TITLE
Question about experiments code

### ISSUE THREAD

**Issue by Dim-1012** [KeiLongW/battery-state-estimation#11]
Hello, I encountered an issue while training the model while trying to replicate your project.NotImplementedError: Layer ModuleWrapper was created by passingnon-serializable argument values in `__init__()`,and therefore the layer must override `get_config()` inorder to be serializable. Please implement `get_config()`.Can you provide an answer
![f96d34cb30a7cb17293ced6d532cc24](https://github.com/KeiLongW/battery-state-estimation/assets/152522655/98942dac-4340-457e-a208-4d43f00a3a7e)

**Comment by KeiLongW** [comment]
which version of tensorflow you are using?  pls show your full code.

**Comment by Dim-1012** [comment]
Thank you for your reply. I am using tensorflow2.2.Code for your battery-state-estimation/experiments/lg/lstm_soc_percentage_lg_all_temp.ipynb

**Comment by KeiLongW** [comment]
I recommend to test with tensorflow version 2.4.1 as it is the version we used

**Comment by Dim-1012** [comment]
Thank you for your guidance. I have resolved this issue. Thank you again
