### ISSUE TITLE
file size

### ISSUE THREAD

**Issue by wyfwyfwyfwyfwyfwyf** [KeiLongW/battery-state-estimation#15]
Hello,I used your code unibo_powertools_data.py.I find that PROCESSED_RESULT_DATA_PATH = 'data/unibo-powertools-dataset/test_result_final.csv',the file'test_result_final.csv' is already included in unibo dataset,if I run this code,origin data will be replaced.Besides,'test_result.csv' is too big to run in all the unibo.ipynb(the process is died).What can I do to solve problems above?

**Comment by KeiLongW** [comment]
It is probably that your device doesn't have enough memory to process the CSV. Use colab or increase your memory size
