### ISSUE TITLE
battery-state-estimation

### ISSUE THREAD

**Issue by Mi12Mi12Cu** [KeiLongW/battery-state-estimation#5]
Hello trying to run your code getting an error could you please help .
![battery-state-estimation](https://user-images.githubusercontent.com/82485291/128954572-4196e252-82d1-4a55-a485-4462e1e02b0d.PNG)

**Comment by KeiLongW** [comment]
Hello. If you use Google Colab, please make sure you have the `data_processing` directory and the py files under your google drive directory `/content/drive/My Drive/battery-state-estimation/battery-state-estimation/`.

**Comment by Mi12Mi12Cu** [comment]
Thanks very much, i was able to sort in out. And your'e right i needed to place in google drive directory
